language: python
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
addons:
apt_packages:
  - libbz2-dev
  - libhdf5-serial-dev
  - liblzo2-dev
#allows for python3.7 testing in travis ci
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas
  scipy matplotlib seaborn scikit-learn numba
- source activate testenv
- conda install pytables
- pip install Cython --install-option="--no-cython-compile"
- pip install .
script: py.test
notifications:
  slack: context-lab:gLtt8NuYpyBW0ZkmwMJGtZut
